- hosts: all
  sudo: yes
  tasks:
#    - yum: name=* state=latest
    - yum: name=libselinux-python
    - selinux: state=disabled
    - yum: name=ntp
    - service: name=ntpd state=started enabled=yes
    - yum: name=dstat
    - yum: name="{{item}}" state=installed
      with_items:
        - "@Development Tools"
    - shell: curl -L https://td-toolbelt.herokuapp.com/sh/install-redhat-td-agent2.sh | sh
      args:
        creates: /etc/td-agent/td-agent.conf
    - shell: /usr/sbin/td-agent-gem install fluent-plugin-dstat ; /usr/sbin/td-agent-gem list 2>&1 | grep fluent-plugin | while read line; do touch /opt/td-agent/installed-$line ; done
      args:
        creates: /opt/td-agent/installed-fluent-plugin-dstat
    - shell: /usr/sbin/td-agent-gem install fluent-plugin-graphite ; /usr/sbin/td-agent-gem list 2>&1 | grep fluent-plugin | while read line; do touch /opt/td-agent/installed-$line ; done
      args:
        creates: /opt/td-agent/installed-fluent-plugin-graphite
    - shell: /usr/sbin/td-agent-gem install fluent-plugin-config-expander ; /usr/sbin/td-agent-gem list 2>&1 | grep fluent-plugin | while read line; do touch /opt/td-agent/installed-$line ; done
      args:
        creates: /opt/td-agent/installed-fluent-plugin-config-expander
    - shell: /usr/sbin/td-agent-gem install fluent-plugin-flatten-hash ; /usr/sbin/td-agent-gem list 2>&1 | grep fluent-plugin | while read line; do touch /opt/td-agent/installed-$line ; done
      args:
        creates: /opt/td-agent/installed-fluent-plugin-flatten-hash
    - template: src=templates/td-agent.conf.j2 dest=/etc/td-agent/td-agent.conf owner=root group=root mode=644
      notify: reload_td-agent
    - service: name=td-agent state=started enabled=yes
    - template: src=templates/iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=600
      notify: reload_iptables
  handlers:
    - name: reload_td-agent
      service: name=td-agent state=reloaded
    - name: reload_iptables
      service: name=iptables state=reloaded

- name: hosts
  hosts: all
  sudo: yes
  tasks:
    - lineinfile: dest=/etc/hosts regexp="{{item.regexp}}" line="{{item.line}}"
      with_items:
        - regexp: ".* mon00$"
          line: "192.168.33.10 mon00"
        - regexp: ".* mon01$"
          line: "192.168.33.11 mon01"
        - regexp: ".* mon02$"
          line: "192.168.33.12 mon02"

- name: graphite/carbon/whisper
  hosts: mon00
  sudo: yes
  tasks:
    - yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - yum: name="{{item}}"
      with_items:
          - memcached
          - python-pip
          - python-carbon
          - python-whisper
          - graphite-web
          - httpd
          - mysql-server
          - MySQL-python
    - service: name=memcached state=started enabled=yes
    - template: src=templates/storage-schemas.conf.j2 dest=/etc/carbon/storage-schemas.conf owner=root group=root mode=644
    - service: name=carbon-cache state=started enabled=yes
    - service: name=mysqld state=started enabled=yes
    - template: src=templates/local_settings.py.j2 dest=/etc/graphite-web/local_settings.py owner=root group=root mode=644
    - mysql_db: name=graphite-web encoding=utf8
    - mysql_user: name=graphite password=graphass append_privs=true priv=graphite-web.*:ALL
    - mysql_user: name=graphite password=graphass append_privs=true priv=graphite-web.*:ALL host=%
    - django_manage: command=syncdb app_path=/usr/lib/python2.6/site-packages/graphite
    - service: name=httpd state=started enabled=yes
    - yum: name=https://grafanarel.s3.amazonaws.com/builds/grafana-2.1.3-1.x86_64.rpm
    - yum: name=grafana
    - service: name=grafana-server state=started enabled=yes
